    const TRANSLATIONS = {
      en: {
        'nav-edu':      'Education',
        'nav-research': 'Research',
        'nav-exp':      'Experience',
        'nav-skills':   'Skills',
        'nav-contact':  'Contact',

        'hero-label': 'HCI Researcher · Full-Stack · Multi-Agent Systems',
        'hero-desc':  'Graduate researcher at NTU designing human–AI collaboration systems for creative workflows. Building the future of animation pre-production through multi-agent orchestration.',
        'btn-research': 'View Research',
        'btn-contact':  'Get In Touch',

        'meta-loc-label':   'Location',
        'meta-loc-val':     'Taipei, Taiwan',
        'meta-deg-label':   'Degree',
        'meta-deg-val':     'M.S. NTU',
        'meta-exp-label':   'Expected',
        'meta-exp-val':     'Aug 2026',
        'meta-email-label': 'Email',

        'sec-edu':      'Education',
        'sec-research': 'Research & Projects',
        'sec-exp':      'Experience',
        'sec-skills':   'Skills',
        'sec-awards':   'Awards & Recognition',

        'edu1-school':   'National Taiwan University',
        'edu1-degree':   'M.S. — Graduate Institute of Networking & Multimedia',
        'edu1-period':   'Sep 2023 → Aug 2026 (Expected)',
        'edu1-details':  'College of Electrical Engineering & Computer Science<br>Interactive Graphics Lab · Communications & Multimedia Lab',
        'edu2-school':   'National Taipei Univ. of Technology',
        'edu2-degree':   'B.S. — Interaction Design (Multimedia)',
        'edu2-period':   'Sep 2019 → Jun 2023',
        'edu2-details':  'GPA: 3.98 / 4.0',

        'r1-type':  "Master's Research",
        'r1-badge': '✦ Live',
        'r1-body':  'Designed and implemented a multi-stage system coordinating AI agents with human creative directors across the animation pipeline — from concept through storyboard.',
        'r1-cta':   'View Paper',
        'r2-type':  'Research Collaboration',
        'r2-badge': '🔒 Private',
        'r2-title': 'Room Palate: Generative AI for Personalized Interior Design',
        'r2-body':  'Built the frontend and integrated backend APIs for a generative design platform, enabling non-technical users to train and apply LoRA-fine-tuned Stable Diffusion models.',
        'r2-lock':  'Not publicly available',

        'exp1-period':  'Jun 2024 → Aug 2024',
        'exp1-role':    'Data Engineering Intern',
        'exp1-b1':      'Engineered and optimized data pipelines, including migration across multiple databases.',
        'exp1-b2':      'Structured large-scale production data for Qlik dashboards and BI reporting.',
        'exp1-b3':      'Stack: Python · SQL · Apache Kafka · Jira',
        'exp2-period':  'Feb 2024 → Jun 2025',
        'exp2-role':    'President',
        'exp2-company': 'NTU Graduate First Female Dormitory Student Council',
        'exp2-b1':      'Led cross-dormitory events and student governance.',
        'exp2-b2':      'Implemented policy improvements to enhance resident experience.',
        'exp3-period':  'Feb 2020 → Jun 2023',
        'exp3-role':    'IT Systems Support',
        'exp3-company': 'Computer and Information Networking Center, NTUT',
        'exp3-b1':      'Technical support and maintenance for university computer-equipped classrooms.',
        'exp3-b2':      'Resolved hardware, network, audio, and software issues.',

        'skill-title1': 'Technical Proficiency',
        'skill-title2': 'Languages & Frameworks',
        'skill-title3': 'Research Focus',
        'skill1': 'Python / Data Engineering',
        'skill2': 'React / TypeScript',
        'skill3': 'LLM Fine-tuning & Agents',
        'skill4': 'Stable Diffusion / GenAI',
        'skill5': 'SQL / Data Pipelines',

        'aw1-title':  'Outstanding International Graduate Student Scholarship',
        'aw1-period': 'NTU · 2023–2025 · Annual',
        'aw1-desc':   'Full tuition waiver plus NTD 65,000 stipend per semester, awarded for academic excellence.',
        'aw2-title':  'Ministry of Education Skills Competition — Makerthon',
        'aw2-period': '2022 · Regional → National',
        'aw2-desc':   'Advanced from Regional (Northern) to National round with Merit Awards at both stages.',
        'aw3-title':  'Near-Perfect Undergraduate GPA',
        'aw3-period': 'NTUT · 2019–2023',
        'aw3-desc':   '3.98 / 4.0 while working in IT support and competing nationally in design competitions.',

        'contact-headline': "Let's build something <em>remarkable.</em>",
        'footer-right':     'NTU · GINM · HCI Researcher',

        'chat-name':        "Jin Ping's AI Assistant",
        'chat-status':      '● Online — ask me anything',
        'chat-placeholder': 'Ask something...',
        'chat-init':        "Hi! I'm Jin Ping's AI assistant. Ask me about her research, skills, or experience! ✦",
        'sugg1': 'Research topics?',
        'sugg2': 'Technical skills?',
        'sugg3': 'Work experience?',
        'sugg4': 'Awards & GPA?',

        'typing-roles': [
          'M.S. Researcher @ NTU',
          'Multi-Agent Systems Designer',
          'React + TypeScript Developer',
          'Generative AI Engineer',
          'HCI Researcher',
        ],
      },

      zh: {
        'nav-edu':      '學歷',
        'nav-research': '研究',
        'nav-exp':      '經歷',
        'nav-skills':   '技能',
        'nav-contact':  '聯絡',

        'hero-label': '人機互動研究員 · 全端開發 · 多代理系統',
        'hero-desc':  '國立臺灣大學碩士研究生，專注於設計人機協作系統以支援創意工作流程。透過多代理協作技術，打造動畫前製的未來。',
        'btn-research': '查看研究',
        'btn-contact':  '與我聯絡',

        'meta-loc-label':   '地點',
        'meta-loc-val':     '台北，台灣',
        'meta-deg-label':   '學位',
        'meta-deg-val':     '碩士 臺大',
        'meta-exp-label':   '預計畢業',
        'meta-exp-val':     '2026 年 8 月',
        'meta-email-label': '信箱',

        'sec-edu':      '學歷',
        'sec-research': '研究與專案',
        'sec-exp':      '工作經歷',
        'sec-skills':   '技能',
        'sec-awards':   '獲獎與榮譽',

        'edu1-school':   '國立臺灣大學',
        'edu1-degree':   '碩士 — 網路與多媒體研究所',
        'edu1-period':   '2023年9月 → 2026年8月（預計）',
        'edu1-details':  '電機資訊學院<br>互動圖形實驗室 · 通訊與多媒體實驗室',
        'edu2-school':   '國立臺北科技大學',
        'edu2-degree':   '學士 — 互動設計（多媒體）',
        'edu2-period':   '2019年9月 → 2023年6月',
        'edu2-details':  'GPA: 3.98 / 4.0',

        'r1-type':  '碩士論文',
        'r1-badge': '✦ 可查閱',
        'r1-body':  '設計並實作跨多階段動畫前製流程的系統，協調 AI 代理與人類創意總監的協作——從概念發想到故事板繪製。',
        'r1-cta':   '查看論文',
        'r2-type':  '研究合作',
        'r2-badge': '🔒 未公開',
        'r2-title': 'Room Palate：個人化室內設計生成式 AI 工具',
        'r2-body':  '開發前端界面並整合後端 API，打造以使用者為核心的生成式設計平台，讓非技術用戶也能訓練並應用 LoRA 微調的 Stable Diffusion 模型。',
        'r2-lock':  '非公開專案',

        'exp1-period':  '2024年6月 → 2024年8月',
        'exp1-role':    '資料工程實習生',
        'exp1-b1':      '設計並優化資料管線，包含跨多資料庫的資料遷移與整合。',
        'exp1-b2':      '處理大規模生產資料，支援 Qlik 儀表板與商業智慧報表。',
        'exp1-b3':      '技術棧：Python · SQL · Apache Kafka · Jira',
        'exp2-period':  '2024年2月 → 2025年6月',
        'exp2-role':    '宿委會會長',
        'exp2-company': '臺灣大學研究生第一女宿宿委會',
        'exp2-b1':      '統籌跨宿舍活動及學生自治事務。',
        'exp2-b2':      '推動宿舍政策改善，提升住宿生活品質。',
        'exp3-period':  '2020年2月 → 2023年6月',
        'exp3-role':    '資訊系統支援',
        'exp3-company': '國立臺北科技大學 計算機與網路中心',
        'exp3-b1':      '提供全校電腦教室的技術支援與系統維護。',
        'exp3-b2':      '排除硬體、網路、音響及軟體等各類問題。',

        'skill-title1': '技術能力',
        'skill-title2': '程式語言與框架',
        'skill-title3': '研究方向',
        'skill1': 'Python / 資料工程',
        'skill2': 'React / TypeScript',
        'skill3': 'LLM 微調與代理系統',
        'skill4': 'Stable Diffusion / 生成式 AI',
        'skill5': 'SQL / 資料管線',

        'aw1-title':  '優秀國際研究生獎學金',
        'aw1-period': '臺大 · 2023–2025 · 每年頒發',
        'aw1-desc':   '因卓越學業表現獲頒，每學期享全額學費減免及新台幣 65,000 元生活津貼。',
        'aw2-title':  '教育部技藝競賽 — Makerthon',
        'aw2-period': '2022 · 北區 → 全國',
        'aw2-desc':   '從北區晉級全國決賽，於兩個競賽階段均榮獲優等獎。',
        'aw3-title':  '近滿分大學成績',
        'aw3-period': '臺北科大 · 2019–2023',
        'aw3-desc':   '在兼任資訊支援工作及參加全國競賽的情況下，仍維持 3.98/4.0 的優異學業成績。',

        'contact-headline': '讓我們一起打造<em>不凡的作品。</em>',
        'footer-right':     '臺大 · 網媒所 · 人機互動研究員',

        'chat-name':        '吳靖萍的 AI 助理',
        'chat-status':      '● 上線中——歡迎提問',
        'chat-placeholder': '問我任何事...',
        'chat-init':        '嗨！我是靖萍的 AI 助理，歡迎詢問她的研究、技能或工作經歷！✦',
        'sugg1': '研究主題？',
        'sugg2': '技術技能？',
        'sugg3': '工作經歷？',
        'sugg4': '獲獎與成績？',

        'typing-roles': [
          '臺大碩士研究生',
          '多代理系統設計師',
          'React + TypeScript 開發者',
          '生成式 AI 工程師',
          '人機互動研究員',
        ],
      },
    };


    let typingRoles  = [];
    let typingIndex  = 0;  
    let charIndex    = 0; 
    let isDeleting   = false;
    let typingTimer  = null;

    let currentLang = 'en';
